### ISSUE TITLE
Need slack channel for iburn

### ISSUE THREAD

**Issue by andrewljohnson** [Burning-Man-Earth/iBurn-iOS#16]
Need it so bad.

**Comment by davidchiles** [comment]
I can get on this

**Comment by andrewljohnson** [comment]
done

**Comment by OnlyInAmerica** [comment]
Can we get the whole Burning-Man-Earth org in on this?

**Comment by andrewljohnson** [comment]
Who is missing now? I invited David/David/Chris/Savannah/Johnstone.

I can make anyone admins.

Andrew Johnson
Founder
*gaiagps.com <http://gaiagps.com>*
