### ISSUE TITLE
Refactor search BRCMapViewController and BRCFilteredTableViewController

### ISSUE THREAD

**Issue by davidchiles** [Burning-Man-Earth/iBurn-iOS#17]
Refactor BRCMapViewController and BRCFilteredTableViewController and pull out the common code used for full-text search, and swipe-to-favorite cells.

**Comment by chrisballinger** [comment]
I tried this in the search-results branch and failed. UISearchController does not work well when trying to display the search bar on the map view.

**Comment by chrisballinger** [comment]
Somewhat refactored...
