### ISSUE TITLE
Enhance BRC POI support

### ISSUE THREAD

**Issue by OnlyInAmerica** [Burning-Man-Earth/iBurn-iOS#26]
Search should surface BRC "utilities" like:

+ First Aid / Ranger Stations
+ Ice
+ Bathrooms?

Major BRC art and events should be included in data:

+ Gates open / close
+ Man / Man Burn
+ Temple / Temple Burn
+ Satellite flyover? 
+ Core Burn
+ Art piece burn

**Comment by chrisballinger** [comment]
Boo ya! Got first aid and bathroom finder
