### ISSUE TITLE
Better Accessibility of List Header Controls

### ISSUE THREAD

**Issue by OnlyInAmerica** [Burning-Man-Earth/iBurn-iOS#44]
In list views where there are controls at the top (search, day picker) it can be a pain having to scroll all the way to top to access these controls (especially because our list views can become very long). Any of the following would be awesome improvements:

+ Header controls were sticky
+ You could quick return to the top of the list where header controls are visible
+ Header controls would re-appear at the first upward scroll.
+ A "Fast scrolling" widget for the lists

**Comment by chrisballinger** [comment]
Double tap on nav bar scrolls to top, however, I want to add double-tap on Tabbar icon to scroll to top.

Also the "fast scroll/jump to" indexes are a definite feature I'd like to have. Yap has built-in support for making this easy, but I haven't implemented it yet.

**Comment by OnlyInAmerica** [comment]
Oh the double-tap thing is great. FWIW double-tap seems like it has to be in the "Signal / Time / Battery area", not the title area where "Events".

**Comment by chrisballinger** [comment]
Yeah that's a feature built-in to iOS so you'll have to take that up with
Apple :)

**Comment by chrisballinger** [comment]
Now have multiple ways to jump back to the top (fast scroll and tabbar tap)
