### ISSUE TITLE
Navigation Mode sets reasonable initial view bounds

### ISSUE THREAD

**Issue by OnlyInAmerica** [Burning-Man-Earth/iBurn-iOS#45]
Starting navigation puts the map into "compass" mode at the current zoom level. Attempting to change this zoom level exits compass mode, so it would be nice if the initial view bounds / zoom was optimized.

e.g: If I navigate from the default map state, I get the following:
![navigation](http://i.imgur.com/g7pYVVP.png)

**Comment by chrisballinger** [comment]
Really? I thought I was able to zoom in and out.

This should be easy to fix because I already have a method that does that
for other views though.

**Comment by chrisballinger** [comment]
Fixed!
