### ISSUE TITLE
Can't download submodule to build app

### ISSUE THREAD

**Issue by cliffspencer** [Burning-Man-Earth/iBurn-iOS#57]
Prompt$ git submodule update --init
Submodule 'Submodules/ASDayPicker' (git@github.com:chrisballinger/ASDayPicker.git) registered for path 'Submodules/ASDayPicker'
Submodule 'Submodules/DOFavoriteButton' (git@github.com:chrisballinger/DOFavoriteButton.git) registered for path 'Submodules/DOFavoriteButton'
Submodule 'Submodules/iBurn-Data' (git@github.com:Burning-Man-Earth/iBurn-Data.git) registered for path 'Submodules/iBurn-Data'
Cloning into 'Submodules/ASDayPicker'...
Warning: Permanently added the RSA host key for IP address '[deleted]' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:chrisballinger/ASDayPicker.git' into submodule path 'Submodules/ASDayPicker' failed

**Comment by bartek75** [comment]
same here

**Comment by manpreetg** [comment]
facing Same problem.

**Comment by manpreetg** [comment]
@cliffspencer @bartek75  use a verified github account to download the module. Also add your ssh key to your account for the computer you are using. This resolved my problem.

**Comment by cliffspencer** [comment]
Thanks, I’ll try that.
