### ISSUE TITLE
Use vector tiles

### ISSUE THREAD

**Issue by davidchiles** [Burning-Man-Earth/iBurn-iOS#6]
Instead of using raster tiles (.png) it would save a lot of space to user vector tiles.

It looks like there's [blocker](https://github.com/mapbox/mapbox-gl-native/issues/584) with [MapBoxGL Native](https://github.com/mapbox/mapbox-gl-native).

Once the native library can use mbtiles as a source we just need to move to use MapBox-Studio.

**Comment by andrewljohnson** [comment]
Probably not worth it, but FWIW Gaia does vector tiles with Maply/Whirlyglobe. If you use that framework, @jessecrocker could probably cut/host the tiles.

**Comment by chrisballinger** [comment]
Done!
