### ISSUE TITLE
clarification on mbtile.jar file

### ISSUE THREAD

**Issue by johndpope** [Burning-Man-Earth/iBurn-iOS#60]
I'm looking to implement an offline mbtile app - and noticed the more recent release is using .jar suffix instead of simply .mbtile - I tried renaming it - or unarchiving it - but no joy. 
Did you guys successfully style the tiles using an external json mapbox style file?

**Comment by chrisballinger** [comment]
It's just an mbtile file renamed to jar to (ab)use CloudFlare's supported file types. Btw it will only work with the legacy mapbox sdk not the latest one.

**Comment by johndpope** [comment]
fyi https://github.com/mousebird/WhirlyGlobe/issues/641
