### ISSUE TITLE
Test Flight build is over 100MB cellular limit

### ISSUE THREAD

**Issue by davidchiles** [Burning-Man-Earth/iBurn-iOS#66]
Is there a way we could get the app size bellow the 100MB limit as to allow downloads over cellular connections?

**Comment by chrisballinger** [comment]
Oh fuckkkkkk

**Comment by chrisballinger** [comment]
The .ipa file itself is only 36.7 MB...

**Comment by davidchiles** [comment]
Seems like this will not be an issue for the official release.
