### ISSUE TITLE
Ability to update data files without app update

### ISSUE THREAD

**Issue by davidchiles** [Burning-Man-Earth/iBurn-iOS#7]
In the past every time data changes the app needed to be resubmitted to the app store, which creates long delays.

### `HTTP` file requests
- [x] Server API with a way to protect embargoed camp placement data (obfuscated URL on S3?)
- [x] Check if files have changed (metadata JSON)
- [x] Push Notifications?
- [x] Background app refresh

### P2P using [AirShare](https://github.com/chrisballinger/AirShare). Pushed back to 2016
- [X] ~~Bluetooth~~
- [X] ~~Apple's multipeer connectivity framework~~

## Files
- [x] mbtiles
- [x] json files (art, camps, events, date_info)

**Comment by andrewljohnson** [comment]
just do mbtiles and json on s3, have app check if files have changed

We have been talking about this feature since beginning of iBurn... do it in simplest possible way and iterate next year. This is really important to get the app getting better each year, instead of being stagnant-ish.

**Comment by chrisballinger** [comment]
Added info about S3 API and updates spec: https://github.com/burning-man-earth/iburn-data#iburn-api-data-updates

**Comment by chrisballinger** [comment]
Started work on the new importer in the [data-import](https://github.com/Burning-Man-Earth/iBurn-iOS/tree/data-import) branch.
