### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by gran33** [Burning-Man-Earth/iBurn-iOS#71]
Hi, 
After doing all steps I'm keep getting this error:
```
Undefined symbols for architecture x86_64:
  "_kBRCMapBoxStyleURL", referenced from:
      __TFE5iBurnCSo10MGLMapView15brc_setDefaultsfT_T_ in MGLMapView+iBurn-EEFA9CAFD11D6D6F.o
  "_kBRCMapBoxAccessToken", referenced from:
      -[BRCAppDelegate application:didFinishLaunchingWithOptions:] in BRCAppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any idea how to handle it?

Thanks in advance.

**Comment by chrisballinger** [comment]
Fill in empty string

**Comment by gran33** [comment]
What is a valid/possible value?

**Comment by chrisballinger** [comment]
Are you looking become to contributor or just checking it out? We have some new features we're working on for this year and could use some help. Send me an email if you have some time to chat

**Comment by gran33** [comment]
I m working on a MidBurn iOS app for the Israeli burning man event. The Israeli Mid burn event is the 3rd biggest burning man like event in the world.

Currently there is only an Android app and I'm palling to work on the iOS version.

**Comment by gran33** [comment]
Another issue during the first run:
`'clientKey' should not be nil.'`

Can help?

**Comment by chrisballinger** [comment]
You should make an account on mapbox.com and input a real API key (aka
style URL)

**Comment by chrisballinger** [comment]
p.s. if you reuse this code please make sure to respect our hard work and
the MPL 2.0 license. Essentially just credit iBurn (and its authors) and
open source any modifications you make to our code.

Ideally we would eventually be able to make the app generic and reusable
for other regionals, but there's currently a lot of stuff hardcoded for the
main event.
