### ISSUE TITLE
Not all playa events seem to be included. 

### ISSUE THREAD

**Issue by chris-340** [Burning-Man-Earth/iBurn-iOS#86]
Hi there! 
It's the first time I'm using this app and it's amazing, thank you so, so much for all your work!!! 

Unfortunately though not all playa events that are listed on the website (https://playaevents.burningman.org/2017/playa_events/1) seem to have made it into the app. 
I noticed this when looking for my own classes which can be found on online (https://playaevents.burningman.org/playa_event/search/2017?search=forr%C3%B3) but not in the app. 
Is the app's data set supposed to include all events that are on the bm-website or only those that also made into the program booklet? 
Would be great if this could be fixed. 

Dusty hugs, 
Chris

**Comment by chrisballinger** [comment]
There is another update in the Apple approval queue. If the PlayaEvents website is correct, the app should update itself in the next few days.
