### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by davidchiles** [Burning-Man-Earth/iBurn-iOS#9]
Some helpful hints on what the app can do on first launch.

**Comment by chrisballinger** [comment]
https://github.com/mamaral/Onboard ?

**Comment by chrisballinger** [comment]
Some more ideas:

- [ ] Prompt for home camp on first launch. Show location for camp if we have it and ask if it looks OK or needs correction. If we don't have location for it, or its wrong, allow users to submit an update.
- [ ] Collect stats for user's home camp.
- [ ] Collect stats for users not going this year.
- [ ] Encourage users to share the app with friends and engage on social media
